// APP
export const SET_CATEGORY_DATA = 'SET_CATEGORY_DATA'

// BROWSE
export const SET_ACTIVE_CATEGORY = 'SET_ACTIVE_CATEGORY'
export const SET_ACTIVE_CONTENT = 'SET_ACTIVE_CONTENT'
export const SET_ACTIVE_ITEM_ID = 'SET_ACTIVE_ITEM_ID'

// BROWSE -> FILTER-BOX
export const SET_FILTER_VALUE = 'SET_FILTER_VALUE'

// BROWSE -> ITEM-LIST
export const OPEN_INFO_PANEL = 'OPEN_INFO_PANEL'
export const TOGGLE_INFO_PANEL = 'TOGGLE_INFO_PANEL'
export const TOGGLE_VIEW_MODE = 'TOGGLE_VIEW_MODE'

// IMPORT
export const ADD_REALM_DATA = 'ADD_REALM_DATA'
