// BROWSE

export const LOAD_CATEGORY_DATA = 'LOAD_CATEGORY_DATA'
export const RESET_FILTER = 'RESET_FILTER'
export const SET_ACTIVE_ITEM = 'SET_ACTIVE_ITEM'
export const SET_FILTER = 'SET_FILTER'
export const TOGGLE_CONTROL_PANEL = 'TOGGLE_CONTROL_PANEL'
export const TOGGLE_VIEW_MODE = 'TOGGLE_VIEW_MODE'
export const UPDATE_ACTIVE_CATEGORY = 'UPDATE_ACTIVE_CATEGORY'
export const UPDATE_ACTIVE_CONTENT = 'UPDATE_ACTIVE_CONTENT'

// IMPORT

export const ADD_REALM_DATA = 'ADD_REALM_DATA'
